# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ff32509fa7b1370585cb5bd565f83731b7bd792a98e64ca10a41e45469aba30dabd04c714162a2d76e5106ef673392c8ebdec4b4acc47ecfbe680bb0c380f19

test:
  secret_key_base: afdce41934518c73c5126e6b41b4b62e75b04dd0d6a726cead33de7093fdc54ab98c815fe430f091071d3b949e3e4ddd6fe9a2464c78955ddad0f4172c539f73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
